### ISSUE TITLE
音频质量差，偶有回音噪音

### ISSUE THREAD

**Issue by lszhangfan** [zijingcloud/Android-SDK#1]
* 机型：华为V9e，中兴b860av
* Android系统版本：
* SDK版本:  1.8.10
* 合作伙伴：朗新科技
* 项目名称：河南省智慧党建

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 问题描述
机顶盒使用usb摄像头(100-200价位的罗技)，房间不大的情况下有回音和噪音，有时关闭会议后台重建会议效果明显改善。希望能优化音频效果。

**Comment by wzhengo** [comment]
问题现象：创维型号SE818的机顶盒使用罗技摄像头入会，另一端收到的声音有噪音；
问题原因：创维SE818机顶盒，某些品牌的声音采集设备兼容性有问题；
解决方案：更换其他品牌摄像头。经测试，“蓝色妖姬”牌子的摄像头声音正常。
