### ISSUE TITLE
机顶盒版本参会后 发现视频画面居中一小块显示，没有全屏显示

### ISSUE THREAD

**Issue by hfdftl** [zijingcloud/Android-SDK#11]
* 机型：
* Android系统版本：
* SDK版本: zjrtc-v1.8.5.aar
* 合作伙伴：上海扬谷网络科技有限公司
* 项目名称：

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by starcwl** [comment]
not bug, 其它人改了layout
