### ISSUE TITLE
网络切换时自动重连

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/Android-SDK#13]
* 机型：
* Android系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 代码期望的行为
wifi <-> 3g 时，重连入会，而不是断开会议。

**Comment by 6YingJie** [comment]
紫荆云视app已修改，之后会想办法在sdk中加上
