### ISSUE TITLE
测试最佳编码和码率，分辨率等参数

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/Android-SDK#17]
* 机型：
* Android系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by 6YingJie** [comment]
最新版紫荆云视已优化
