### ISSUE TITLE
入会后为接入摄像头在华为盒子上崩溃

### ISSUE THREAD

**Issue by zhangle1225** [zijingcloud/Android-SDK#19]
* 机型：EC6108V9E_4G
* Android系统版本：4.4.4
* SDK版本:  v1.9.3
* Android盒子/手机型号：华为盒子

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 运行代码后复现问题。
入会时，在未插入摄像头的情况下，会导致程序崩溃
### 代码期望的行为
希望捕获住这个异常，并通过callState将错误原因回抛给我们

**Comment by 6YingJie** [comment]
zjrtcv1.9.5已解决
