### ISSUE TITLE
异常退会，会出现画面残留

### ISSUE THREAD

**Issue by lszhangfan** [zijingcloud/Android-SDK#2]
* 机型：华为V9e，中兴b860av
* Android系统版本：
* SDK版本: 1.8.10
* 合作伙伴：朗新科技
* 项目名称：河南省智慧党建

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 问题描述
在安卓sdk异常退出会议后，其他观看方可以看到异常退会者的残留画面，持续数分钟后画面才会消失。我们在使用sdk的时候，进会较慢，有时在进会过程中退出了，重新进会，也会出现这个问题。

**Comment by starcwl** [comment]
残留画面是因为退会者已退出，但是服务器端还无法判断该退会者是否退会。服务器是通过连接超时方式去判断。所以根本上避免该问题还是需要从处理异常退出着手。先关闭此issue。如果有异常退会的现象，请发新issue。
