### ISSUE TITLE
入会后未插入摄像头导致会议状态卡死在call_connecting

### ISSUE THREAD

**Issue by zhangle1225** [zijingcloud/Android-SDK#20]
* 机型：测试机型为中兴  ZXV10B860AV2-1-a
* Android系统版本：
* SDK版本:v1.9.3
* Android盒子/手机型号：大部分安卓盒子

- [x] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 运行代码后复现问题。
入会后未插入摄像头导致会议状态卡死在call_connecting状态
### 代码期望的行为
通过callState将错误信息回抛给我们

**Comment by 6YingJie** [comment]
已在zjrtcv1.9.5中实现
