### ISSUE TITLE
建议增加入会过程中的背景图片

### ISSUE THREAD

**Issue by gozhangfango** [zijingcloud/Android-SDK#4]
* 机型：
* Android系统版本：
* SDK版本:
* 合作伙伴：朗新科技
* 项目名称：河南党建

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 需求
SDK在入会过程中，画面黑屏，客户体验不好，建议增加一张背景图片，内容是“正在入会，请稍后”，或“信号切入中”之类的提示信息。

**Comment by wzhengo** [comment]
需求已开发完成，会在下个版本更新。
