### ISSUE TITLE
需求：增加隐身入会功能

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/Android-SDK#5]
* 机型：
* Android系统版本：
* SDK版本:
* 合作伙伴：朗新
* 项目名称：

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 代码期望的行为
我加入这个会议，能看见会议视频和音频，但是会议中的其他人不知道我的存在
### 代码实际的行为

**Comment by starcwl** [comment]
rtc.hideme = true;
rtc.makeCall(host, alias, displayName, null, 'recvonly');

**Comment by 6YingJie** [comment]
在最新的zjrtc-v1.9.4.aar中已加入了设置是否隐身入会的方法setHideMe(boolean hideMe)
