### ISSUE TITLE
图片分享控制页偶发不出现

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/Android-SDK#7]
* 机型：
* Android系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by 6YingJie** [comment]
1.分享一张图片，在远程接收到图片时，远程显示图片的同时，本地的图片会消失一下，有时图片就显示不出来
2.分享两张或多张图片，在远程接收到图片时，远程显示图片的同时，本地的图片会消失一下，有时显示出来的图片与远程的不一致，有时显示不出来。

推测：本地显示图片和共享图片到远程是两个线程，本地显示图片和远程显示图片都会控制 图片切换控制界面的state，两个控制的时间先后顺序不确定，导致图片切换控制界面偶尔显示不出来。

**Comment by 6YingJie** [comment]
最新版紫荆云视已修复
