### ISSUE TITLE
切换到后台几分钟后会议断开

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/Android-SDK#8]
* 机型：
* Android系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by 6YingJie** [comment]
紫荆云视app会议界面已加上开启前台服务，按home键后会在桌面显示一个小的悬浮窗，后续会集成到sdk中并暴露开启服务的接口
