### ISSUE TITLE
 android SDK V1.8.10版，设置上行分辨率、码率没有生效

### ISSUE THREAD

**Issue by Xyanwu** [zijingcloud/Android-SDK#9]
* 机型：
* Android系统版本：
* SDK版本:  android版SDK，1.8.10
* 合作伙伴：朗新科技
* 项目名称：河南党建

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

描述：
        android SDK V1.8.10版，设置上行分辨率、码率没有生效。

**Comment by wzhengo** [comment]
经测试，android SDK V1.8.10版，设置上行分辨率、码率确认是可以生效的。
请参考demo和使用说明文档，检查设置方法是否正确。

**Comment by zijingcloud** [comment]
没有反馈，因此先关闭问题，若未解决，请回复
